### ISSUE TITLE
Question about complete decisiveness output

### ISSUE THREAD

**Issue by rsk222** [josephwb/Decisivator#13]
Hello,
I have been using Decisivator with a data set and am somewhat confused about the output and summary status when I use the complete decisiveness metric. When I run the T option, I get the following output:
Searching for presence of all possible taxon triplets...
  Triplet: 131071 of 134044
Counted 134044 total triplets, 134044 of which were observed.
 Woo-hoo! All possible taxon triplets observed. Matrix is (probably) decisive for all possible trees!

Searching for presence of all possible taxon quartets...
  Quartet: 3047423 of 3049501
Counted 3049501 total quartets, 3049501 of which were observed.
 Woo-hoo! All possible taxon quartets observed. Matrix IS decisive for all possible trees!

So it seems that the matrix is decisive. But when I print the summary info, I get this:

1 processor available for analysis.
Input file: 'Input.nexus'.
A total of 2139 partitions read for 94 taxa.

No reference taxa found (i.e. have data for all partitions).
1 user tree in memory.
Matrix coverage is currently at: 0.902365
Taxon-character matrix is NOT currently decisive for all possible trees.
Partial tree-wise decisiveness for taxon-character matrix is currently: 1 (determined from 1000 random trees).
Partial branch-wise decisiveness has not yet been determined for this taxon-character matrix.

This says the matrix is NOT decisive. I didn't make any changes to it, so I am not sure why these things seem to contradict one another. 

Thanks!

**Comment by josephwb** [comment]
Hmm. Sorry about the trouble. It is possible that the value is simply not updated. I can run some tests. Could I troubleshoot with your matrix? phylo.jwb @ gmail.com

**Comment by josephwb** [comment]
Ok this is fixed with d49f289b5a52808aba45f36961b229459e6dac47. As I suspected, a simple failure to update. Sorry about that!
